services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: vessel-core:latest
    container_name: vessel_core
    env_file:
      - .env
    ports:
      - "127.0.0.1:8999:80" # Solo localhost, nginx hace SSL en 10999
    volumes:
      - storage:/var/www/html/storage
      - dbdata:/var/www/html/database

volumes:
  storage:
  dbdata:


networks:
  default:
    external: true
    name: web_default
