services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: vessel-core:latest
    container_name: vessel_core
    env_file:
      - .env
    ports:
      - "${APP_PORT:-10999}:80"
    volumes:
      - storage:/var/www/html/storage
      - dbdata:/var/www/html/database

volumes:
  storage:
  dbdata:
